name: Build and Deploy Astro to cPanel

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro project
        run: pnpm build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts

      - name: Remove existing files except .htaccess
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} \
          'cd ${{ secrets.CPANEL_DEST }} && find . -maxdepth 1 ! -name "." ! -name ".htaccess" -exec rm -rf {} +'

      - name: Deploy dist to cPanel via rsync
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.CPANEL_PORT }}" \
          dist/ ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }}:${{ secrets.CPANEL_DEST }}/
